---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/images
  label: Images
  create: documents
  match: "**/*"
- type: document
  path: src
  label: theme
  read_only: true
- type: directory
  path: photographer/src/pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: js
- type: directory
  path: src/components
  label: Components
  create: documents
  match: "**/*"
upload_dir: Images
public_path: src/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
